### ISSUE TITLE
lineageOS 20 Build Source error when I use the device cannon

### ISSUE THREAD

**Issue by snyyns** [xiaomi-mt6853-devs/android_device_xiaomi_cannon#2]
![1701847570513](https://github.com/xiaomi-mt6853-devs/android_device_xiaomi_cannon/assets/141186016/52267c0d-883d-48d8-816e-0831e4257885)

when i comment these codes in  device/xiaomi/cannon/device.mk appear these errors (these packages do not find in phone,so i comment)

**[  1% 264/15154] //system/sepolicy:recovery_sepolicy.cil Building cil for recovery_sepolicy.cil
FAILED: out/soong/.intermediates/system/sepolicy/recovery_sepolicy.cil/android_common/recovery_
sepolicy.cil
out/host/linux-x86/bin/checkpolicy -C -M -c 30 -o out/soong/.intermediates/system/sepolicy/reco
very_sepolicy.cil/android_common/recovery_sepolicy.cil out/soong/.intermediates/system/sepolicy
/recovery_sepolicy.conf/android_common/recovery_sepolicy.conf # hash of input list: a316674d1dc
0868a105f79e687a4b6449e6a8801cfa3253b9c426787c1c40d09
device/xiaomi/cannon/sepolicy/vendor/hal_power_default.te:7:ERROR 'unknown type vendor_power_pr
op' at token ';' on line 91073:
#line 7
allow hal_power_default vendor_power_prop:property_service set;
checkpolicy:  error(s) encountered while parsing configuration**

Would you please tell me how to solve this problem?

**Comment by LinkBoi00** [comment]
Read the error message, it's pretty clear

**Comment by snyyns** [comment]
But this te file is similar to the te file of other device trees, and also does not define this vendor_power_prop type.

**Comment by snyyns** [comment]
如果我额外添加这个vendor_power_prop类型后，又会出现其他错误，我感觉应该是偏离了问题的核心

**Comment by snyyns** [comment]
If I add this additional vendor_power_prop type, there will be other errors, I think it should be deviated from the core of the problem

**Comment by snyyns** [comment]
> Read the error message, it's pretty clear

Would you please tell me how to solve this problem?

**Comment by LinkBoi00** [comment]
You haven't cloned one of the dependencies, like i said read the error

**Comment by LinkBoi00** [comment]
You haven't cloned all dependencies, read your errors and also lineage.dependencies file in the tree

**Comment by gsuzeda** [comment]
i'm having the same problem. i've checked the dependencies and i'm getting the same error.

Steps to reproduce the error:

```
git clone https://github.com/xiaomi-mt6853-devs/android_device_xiaomi_cannon device/xiaomi/cannon  -b lineage-20
git clone https://github.com/xiaomi-mt6853-devs/android_kernel_xiaomi_cannon kernel/xiaomi/cannon  -b lineage-20
git clone https://github.com/xiaomi-mt6853-devs/android_vendor_xiaomi_cannon vendor/xiaomi/cannon
git clone https://github.com/xiaomi-mt6853-devs/android_device_mediatek_sepolicy_vndr device/mediatek/sepolicy_vndr  -b lineage-20
git clone https://github.com/LineageOS/android_hardware_mediatek hardware/mediatek  -b lineage-20
git clone https://github.com/LineageOS/android_hardware_xiaomi hardware/xiaomi -b lineage-20

source build/envsetup.sh
lunch lineage_cannon-userdebug
brunch lineage_cannon-userdebug
```

**Comment by LinkBoi00** [comment]
The original poster 

> i'm having the same problem. i've checked the dependencies and i'm getting the same error.
> 
> Steps to reproduce the error:
> 
> ```
> git clone https://github.com/xiaomi-mt6853-devs/android_device_xiaomi_cannon device/xiaomi/cannon  -b lineage-20
> git clone https://github.com/xiaomi-mt6853-devs/android_kernel_xiaomi_cannon kernel/xiaomi/cannon  -b lineage-20
> git clone https://github.com/xiaomi-mt6853-devs/android_vendor_xiaomi_cannon vendor/xiaomi/cannon
> git clone https://github.com/xiaomi-mt6853-devs/android_device_mediatek_sepolicy_vndr device/mediatek/sepolicy_vndr  -b lineage-20
> git clone https://github.com/LineageOS/android_hardware_mediatek hardware/mediatek  -b lineage-20
> git clone https://github.com/LineageOS/android_hardware_xiaomi hardware/xiaomi -b lineage-20
> 
> source build/envsetup.sh
> lunch lineage_cannon-userdebug
> brunch lineage_cannon-userdebug
> ```

OP has dependency issues, they're probably missing hardware/mediatek. About the sepolicy issues I'll check it out. I have no issues on my side with LineageOS 20

**Comment by LinkBoi00** [comment]
Issue is obvious @gsuzeda, you're not using mediatek sepolicy from LineageOS org. Read [lineage.dependencies](https://github.com/xiaomi-mt6853-devs/android_device_xiaomi_cannon/blob/lineage-20/lineage.dependencies) same for @snyyns.

**Comment by snyyns** [comment]
请问如下问题解决了吗？还是找不到这个属性定义
device/xiaomi/cannon/sepolicy/vendor/hal_power_default.te:7:ERROR 'unknown type vendor_power_prop' at token ';' on line 91077:
#line 7

**Comment by snyyns** [comment]
> Issue is obvious @gsuzeda, you're not using mediatek sepolicy from LineageOS org. Read [lineage.dependencies](https://github.com/xiaomi-mt6853-devs/android_device_xiaomi_cannon/blob/lineage-20/lineage.dependencies) same for @snyyns.

Excuse me, has this problem been solved? The type cannot be found
device/xiaomi/cannon/sepolicy/vendor/hal_power_default.te:7:ERROR 'unknown type vendor_power_prop' at token ';' on line 91077:
#line 7

**Comment by snyyns** [comment]
> i'm having the same problem. i've checked the dependencies and i'm getting the same error.
> 
> Steps to reproduce the error:
> 
> ```
> git clone https://github.com/xiaomi-mt6853-devs/android_device_xiaomi_cannon device/xiaomi/cannon  -b lineage-20
> git clone https://github.com/xiaomi-mt6853-devs/android_kernel_xiaomi_cannon kernel/xiaomi/cannon  -b lineage-20
> git clone https://github.com/xiaomi-mt6853-devs/android_vendor_xiaomi_cannon vendor/xiaomi/cannon
> git clone https://github.com/xiaomi-mt6853-devs/android_device_mediatek_sepolicy_vndr device/mediatek/sepolicy_vndr  -b lineage-20
> git clone https://github.com/LineageOS/android_hardware_mediatek hardware/mediatek  -b lineage-20
> git clone https://github.com/LineageOS/android_hardware_xiaomi hardware/xiaomi -b lineage-20
> 
> source build/envsetup.sh
> lunch lineage_cannon-userdebug
> brunch lineage_cannon-userdebug
> ```

Please use this git.
Https://github.com/LineageOS/android_device_mediatek_sepolicy_vndr.git.
Not this.
Https://github.com/xiaomi-mt6853-devs/android_device_mediatek_sepolicy_vndr.git

**Comment by LinkBoi00** [comment]
I'm closing this, there is no issue with the source

**Comment by KongGuoguang** [comment]
> > i'm having the same problem. i've checked the dependencies and i'm getting the same error.
> > Steps to reproduce the error:
> > ```
> > git clone https://github.com/xiaomi-mt6853-devs/android_device_xiaomi_cannon device/xiaomi/cannon  -b lineage-20
> > git clone https://github.com/xiaomi-mt6853-devs/android_kernel_xiaomi_cannon kernel/xiaomi/cannon  -b lineage-20
> > git clone https://github.com/xiaomi-mt6853-devs/android_vendor_xiaomi_cannon vendor/xiaomi/cannon
> > git clone https://github.com/xiaomi-mt6853-devs/android_device_mediatek_sepolicy_vndr device/mediatek/sepolicy_vndr  -b lineage-20
> > git clone https://github.com/LineageOS/android_hardware_mediatek hardware/mediatek  -b lineage-20
> > git clone https://github.com/LineageOS/android_hardware_xiaomi hardware/xiaomi -b lineage-20
> > 
> > source build/envsetup.sh
> > lunch lineage_cannon-userdebug
> > brunch lineage_cannon-userdebug
> > ```
> 
> Please use this git. [Https://github.com/LineageOS/android_device_mediatek_sepolicy_vndr.git](Https://github.com/LineageOS/android_device_mediatek_sepolicy_vndr.git). Not this. [Https://github.com/xiaomi-mt6853-devs/android_device_mediatek_sepolicy_vndr.git](Https://github.com/xiaomi-mt6853-devs/android_device_mediatek_sepolicy_vndr.git)


That is helpful, thanks.
